[build]
  command = "touch build/index.html"

# block some countries
[[redirects]]
  from = "/*"
  to = "/451.html"
  status = 451
  force = true
  conditions = {Country=["BY","CU","IR","IQ","CI","LR","KP","SD","SY","ZW"]}
  headers = {Link="<https://uniswap.exchange>"}

# forward migrate
[[redirects]]
  from = "https://migrate.uniswap.exchange/*"
  to = "https://uniswap.exchange/migrate/v1"
  status = 301
  force = true